version: "3.9"

services:
  app:
    build: .
    command: python3 /app/cli.py
    volumes:
        - .:/project

  runner: 
    build: .
    command: runner /runner/tests/examples/test_conf.yaml

  setup:
    build: .
#    command: python3 /app/cli.py setup /root/goodbot.yaml
    command: python3 /app/cli.py setup /project/examples/goodbot.yaml
    volumes:
       - .:/project

  record:
    build: .
# This would be the proper command later on.
#    command: python3 /app/cli.py build ./my_example
    command: python3 /app/cli.py record ./toto
    volumes:
      - .:/root
