version: "3.9"

services:
  app:
    build: .
    command: python3 src/cli.py
    volumes:
        - .:/app

  runner: 
    build: .
    command: runner /runner/tests/examples/test_conf.yaml

  setup:
    build: .
    command: python3 src/cli.py setup examples/goodbot.yaml
    volumes:
       - .:/app

  create:
    build: .
    command: python3 src/cli.py build examples/goodbot.yaml
    volumes:
      - .:/app
