version: "3.9"

services:
  app:
    build: .
    command: python3 /app/cli.py
    volumes:
        - ./project:/root

  runner: 
    build: .
    command: runner /runner/tests/examples/test_conf.yaml

  setup:
    build: .
    command: python3 /app/cli.py setup /root/goodbot.yaml
    volumes:
       - ./toto:/root

  create:
    build: .
    command: python3 /app/cli.py build ./my_example
    volumes:
      - ./toto:/root
