version: "3.9"

services:

  app:
    build: .
    command: python3 /app/cli.py
    volumes:
        - .:/project

  runner: 
    build: .
    command: runner /runner/tests/examples/test_conf.yaml

  setup:
    build: .
    command: python3 /app/cli.py setup /project/examples/goodbot.yaml
    volumes:
       - .:/project

  record:
    build: .
    command: python3 /app/cli.py record ./toto
    volumes:
      - .:/root

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: pytest /good-bot-source/.
    volumes:
      - .:/good-bot-source

  test-cov:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /good-bot-source
    command: pytest --cov ./goodbot tests/
    volumes:
      - .:/good-bot-source
