version: "3.9"

services:
  app:
    build: .
    command: python src/cli.py
    volumes:
        - .:/app
  runner: 
    build: .
    command: runner /runner/tests/examples/test_conf.yaml
  parser:
    build: .
    command: python src/cli.py setup example/goodbot.yaml
    volumes:
       - .:/app
