version: "3.9"

services:

  app:
    build:
        context: .
        dockerfile: Dockerfile.dev
    command: python3 /app/goodbot/cli.py
    volumes:
        - .:/project

  runner: 
    build:
        context: .
        dockerfile: Dockerfile.dev
    command: runner /install/good-bot-runner-1.1.0/tests/examples/test_conf.yaml

  setup:
    build:
        context: .
        dockerfile: Dockerfile.dev
    command: python3 /project/goodbot/cli.py setup /project/examples/basics/goodbot.yaml
    volumes:
       - .:/project

  record:
    build:
        context: .
        dockerfile: Dockerfile.dev
    command: python3 /app/goodbot/cli.py record /root/toto
    volumes:
      - .:/root

  render:
    build:
        context: .
        dockerfile: Dockerfile.dev
    command: python3 /app/goodbot/cli.py render ./toto
    volumes:
      - .:/root

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: pytest /good-bot-source/.
    volumes:
      - .:/good-bot-source

  test-cov:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /good-bot-source
    command: pytest --cov ./goodbot tests/
    volumes:
      - .:/good-bot-source
