version: "3.9"

services:
  app:
    build: .
    command: python3 /app/cli.py
    volumes:
        - .:/root

  runner: 
    build: .
    command: runner /runner/tests/examples/test_conf.yaml

  setup:
    build: .
    command: python3 /app/cli.py setup examples/goodbot.yaml
    volumes:
       - .:/root

  create:
    build: .
    command: python3 /app/cli.py build ./toto
    volumes:
      - .:/root
