[tool.poetry]
name = "goodbot"
version = "0.1.0"
description = "Automating the creation of video documentation."
authors = ["TrickyTroll <tricky@beon.ca>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
