[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool]
[tool.poetry]
authors = ["TrickyTroll <53831454+TrickyTroll@users.noreply.github.com>"]
description = "Automating the recording of documentation videos"
license = "MIT"
name = "goodbot"
version = "0.1.0"
[tool.poetry.dependencies]
PyYAML = "^5.4.1"
click = "^7.1.2"
google-cloud-texttospeech = "^2.3.0"
pexpect = "^4.8.0"
python = "^3.8"
pylint = "^2.8.2"
[tool.poetry.dev-dependencies]
