1:
  command: echo
  arguments: "hello, world"
  read: "Hello, world."
2:
  command: ls
  argument: "-a"
  read: "I can run commands."
3:
  command: echo
  arguments: "hello, world"
  read: "Hello, world."
